### ISSUE TITLE
[Feature Request] Automated Symlink of the custom songs folder.

### ISSUE THREAD

**Issue by AlexxSeven** [RiskiVR/BSLegacyLauncher#5]
If at all possible, could automated symbolic links be created for the custom songs folder and the custom WIP folder?

It could utilize user input of beat saber's install location. but also be completely optional. and allow users to keep song libraries from both versions completely in sync.

**Comment by RiskiVR** [comment]
I like the idea, however I don't think it would be possible as the mods specifically load from folders. We'll look into it, but there's no guarantee of success.

**Comment by AlexxSeven** [comment]
Well idk about mod folders. at least for mod folders I'd think it be better for them to stay separate due to file/config compatibility issues that might arise.

But at least for CustomLevels and CustomWIPLevels I can confirm that I had no issues on windows running the game or playing the songs with them as junction links to the primary folders. (they show up to applications as existing there but are actually symlink-ed to the folders in another location.

Edit: This is after manually adding the junctions through the mklink command in CMD

![Powershell of dir command in the legacy installation folder.](https://user-images.githubusercontent.com/8524552/120045971-c42b2300-bfd6-11eb-898c-25a34956b7e9.png)

**Comment by RiskiVR** [comment]
Ah you misunderstood me. I'm saying the actual mod that loads the songs into your game is meant to find the CustomLevels folder, and wasn't made to look for shortcuts or symlinks. If this does work I'll look into giving it a try.

**Comment by AlexxSeven** [comment]
Ah! ok gotcha, yeah I misunderstood on that part.

As far as song loading goes and mods interacting with songs, I haven't noticed any issues with the symlink setup I've got going right now. could be because I'm using junction links? If you do give it a go and need testers I'll be more than happy to give it a try :D

**Comment by GreenMan36** [comment]
I support this, you have Soft links and Hard links, both seem to work fine, I never used junctions before.

I've used a shell extension to quickly link all folders I need, https://schinagl.priv.at/nt/hardlinkshellext/hardlinkshellext.html
You select all folders, can select multiple. Then right-click and press "Pick link source", go to your Legacy game install and right-click, hover "Drop as.." and you can choose a plethora of options.
![Image of HardLinks Shell Extention folder selecting](https://i.imgur.com/lwUFFEY.png)
![Image of HardLinks Shell Extention link drop selecting](https://i.imgur.com/idsLHQh.png)

I do this for all custom content, custom songs and wip songs. Its 1:1 with my previous Beat Saber version and syncs nearly everything.

Its great and would be amazing if it where implemented.


Depending on what type of link you use, it would look exactly the same for whatever program is trying to use it.
I've used this to offload specific games steam onto a SSD without adding an additional library. Also specific big. often used game files and have never experienced issues in this odd situation so it should cause no issues for mods and song loading.

**Comment by RiskiVR** [comment]
Coming back to this, I don't think I'd be able to automatically link custom songs as users usually have their steam install in different locations. Though seeing that you all can do it yourself, is it alright if I close this?

**Comment by AlexxSeven** [comment]
> Coming back to this, I don't think I'd be able to automatically link custom songs as users usually have their steam install in different locations. Though seeing that you all can do it yourself, is it alright if I close this?

Ye this issue can be closed if you don't think you'd be able to manage it automagically or even via user input (such as a "link to original beat saber install location" settings option.)

**Comment by GreenMan36** [comment]
> Coming back to this, I don't think I'd be able to automatically link custom songs as users usually have their steam install in different locations. Though seeing that you all can do it yourself, is it alright if I close this?

Hi, I've taken a look and it should be doable.
On Windows Steam is commonly installed in `C:\Program Files\Steam` however if a user (like me) has changed their location you can just look at the program's list/registry and search for Steam there; it should contain a string to `*\Steam\uninstall.exe` pop off the exe and you got Steam's install location! Should work from Windows XP and up.

There's loads of ways to get this value;
* Powershell; `Get-ItemProperty HKLM:\\Software\\Wow6432Node\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\* | Select-Object DisplayIcon` and grab the line that contains `\Steam\uninstall.exe`.
* With Python I `import winreg` and loop over the entries till I find Steam.
* In C# you should be able to use [RegistryKey.GetValue](https://docs.microsoft.com/en-us/dotnet/api/microsoft.win32.registrykey.getvalue). Or [Registry](https://docs.microsoft.com/en-us/dotnet/api/microsoft.win32.registry) might also be useful.

So that's the Steam installation folder solved but then; what if the game is stored on a different library? Got you, libraryfolders.vdf saves the day!
`\Steam\steamapps\libraryfolders.vdf` stores info of where libraries are stored; the size; and all games stored within!
Stored as 
```
"libraryfolders"
{
	"0"
	{
		"path"		"C:\\Steam"
		"label"		""
		"contentid"		"9108667064157857183"
		"totalsize"		"0"
		"update_clean_bytes_tally"		"2746499860"
		"time_last_update_corruption"		"0"
		"apps"
		{
			"228980"		"855160891"
			"250820"		"5599570151"
		}
	}
	"1"
	{
		"path"		"D:\\Steam"
		"label"		""
		"contentid"		"2346155495115144394"
		"totalsize"		"5999482105856"
		"update_clean_bytes_tally"		"244542332586"
		"time_last_update_corruption"		"0"
		"apps"
		{
			"240"		"4628887753"
			"620980"		"1406563753"
		}
	}
}
```
For example.

So you just find the library that contains `620980` and take `\Steam` and add `\steamapps\common\Beat Saber`
You're done!

This could also be used to allow launching and backing up of the main game for when the game updates for example.
Would be a significant upgrade in my opinion!

**Comment by GreenMan36** [comment]
I'd *really* like to help but I started learning this year so I have 0 knowledge of C#. I do have knowledge of Java but also haven't worked with Unity code, have worked with Unity itself though.

**Comment by RiskiVR** [comment]
This all seems like alot to me, and we already put so much work into getting v1.4.0 out, so the symlink can remain manual. I couldn't ever figure out how to get unity to ask for a specific location since I wouldn't know how to have Unity handle popups and inputs. Thanks for the idea though, enjoy the new bug-free version 💜

**Comment by RiskiVR** [comment]
ComputerElite has created a Batch script for automated Symlinks. You can download it in releases.

**Comment by GreenMan36** [comment]
I'll see if I can make a separate app instead; thanks though the script is neat!

**Comment by GreenMan36** [comment]
Its actually much simpler; you don't need to go through Steam and get the library as you can just do [this.](https://stackoverflow.com/questions/18232972/how-to-read-value-of-a-registry-key-c-sharp)
Its under `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Steam App 620980` with key `InstallLocation`.
![image](https://user-images.githubusercontent.com/5887406/163711667-7138bd25-234c-40ff-b921-57a2e5e63aea.png)
Quite simple to get with `Registry.LocalMachine.OpenSubKey()` and `.GetValue("InstallLocation")`.
