### ISSUE TITLE
What happened? 

### ISSUE THREAD

**Issue by DMatheja** [RiskiVR/BSLegacyLauncher#55]
Can you explain to me why in gods sake do we need audio in an application that should only do its job and nothing more? also it is quite sussy that you need the users name, password and even 2FA. Older LegacyLauncher could do it without any of this.

also why are the old versions gone?
usually they should be available, have you deleted them on purpose?
I cannot trust this, please answer.

**Comment by RiskiVR** [comment]
BSLegacyLauncher has always used credentials since day 1, and there have been many security updates with the older versions being removed to prevent security vulnerabilities. The reason why it uses Steam's login is because it depends on Steam's open source [DepotDownloader](https://github.com/SteamRE/DepotDownloader) tool.
The audio is simply to make the tool fancier, you can disable the ambience in Advanced Settings
